### ISSUE TITLE
wrong constructor parameter for BaseBlockItem

### ISSUE THREAD

**Issue by UpcraftLP** [SandboxPowered/SandboxAPI#7]
BaseBlockItem should take a `Block` instead of `BaseBlock` as constructor parameter.

Plus there should be a constructor that allows passing a custom `Item$Settings` object, for setting stuff like the item group.

**Comment by Boundarybreaker** [comment]
Probably not converted when `Block -> BaseBlock`

**Comment by TheCodedOne** [comment]
No this is actually intentional, people shouldn't be able to make BaseBlockItems of blocks they didn't create, the item settings on the other hand though, that's an oversight.

**Comment by TheCodedOne** [comment]
Fixed in #16
